### ISSUE TITLE
problems with parsing R(s,a,s',o') 

### ISSUE THREAD

**Issue by mgrzes** [dmaniloff/libpomdp#6]
when I parse this file:

discount: 0.75
values: reward
states: tiger-left tiger-right tiger-middle
actions: listen open-left open-right
observations: tiger-left tiger-right

T:listen
identity

T:open-left
uniform

T:open-right
0.85 0.15
0.2 0.8
0.7 0.3

O:listen
0.85 0.15
0.2 0.8
0.7 0.3

O:open-left
uniform

O:open-right
0.1 0.9
0.8 0.2
0.4 0.6

R:open-right : tiger-right : tiger-right : tiger-right -100

R:open-right : tiger-right : tiger-right : tiger-left -20

R:open-right : tiger-right : tiger-left : tiger-left 100

R:open-right : tiger-right : tiger-left : tiger-right -30

the reward for action open-right and state tiger-right is:

R[2][1]
-30.0 -30.0 
-20.0 -20.0 
0.0 0.0 

which means that values -100 and 100 are ignored. I think they should appear in the above matrix as well.

**Comment by dmaniloff** [comment]
@mgrzes thank you for reporting this, and sorry for the looooooong delay!! There were two unrelated bugs that I was able to discover.

97203a4a3e9b9f22397043ced6bdd68e568ec3e5 fixes your specific issue. It seems we were trying to handle multiple reward specs in a single .pomdp file. For now we'll only support either `R(s,a)`, `R(s,a,s')`, or `R(s,a,s',o')`, but not combinations of more than one in the same problem file. Note that for the latter two cases we're compressing the rewards to represent them in the `R(s,a)` format:

`R(s,a) = \sum_s' R(s,a,s') T(s,a,s')`
`R(s,a) = \sum_{s',o'} R(s,a,s',o') T(s,a,s') O(o',a,s')`

There is a small mistake in your problem def, in that your transition for `open-right` is missing a column since this is a 3-state problem. I changed it to look like

```
T:open-right
0.85 0.15 0.0
0.2 0.8 0.0
0.7 0.3 0.0
```

Here's a sample output from loading your file. Remember that the indices for R are 1-based given the vector implementation of matrix-toolkits-java:
http://code.google.com/p/matrix-toolkits-java/source/browse/trunk/src/no/uib/cipr/matrix/AbstractVector.java?r=46#236
so in R[2] below you'll see  index 2 and value -3.220000000000e+01, which actually represents `R[2][1]=-3.220000000000e+01`.

```
Trying to load file: data/problems/tiger/tiger-marek-grzes-2.POMDP ...
PARSER: Parsing preamble...
PARSER: Summary -> states 3
                -> observations 2
                -> actions 3
PARSER: Parsing starting state/belief...
PARSER: Parsing parameters...
PARSER: R(s,a,s',o') reward representation detected, you'll probably run out of memory.
PARSER: Compressing R(s,a,s',o') rewards...
PARSER: [DONE]
This is the loaded POMDP:
Dimensions:
|S|: 3, |A|: 3, |O|: 2
Transition table: 
T[0]
1.0 0.0 0.0 
0.0 1.0 0.0 
0.0 0.0 1.0 
T[1]
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
T[2]
0.85 0.15 0.0 
0.2 0.8 0.0 
0.7 0.3 0.0 
Oservation table: 
O[0]
0.85 0.15 
0.2 0.8 
0.7 0.3 
O[1]
0.5 0.5 
0.5 0.5 
0.5 0.5 
O[2]
0.1 0.9 
0.8 0.2 
0.4 0.6 
Rewards table: 
R[0]
         3                   0
R[1]
         3                   0
R[2]
         3                   1
         2 -3.220000000000e+01
```
